# Конфигурация Kafka для больших файлов
broker.id=1
listeners=PLAINTEXT://:9092
advertised.listeners=PLAINTEXT://dsu-kafka:9092
zookeeper.connect=dsu-zookeeper:2181
log.dirs=/var/lib/kafka/data
num.partitions=3
default.replication.factor=1
min.insync.replicas=1
message.max.bytes=52428800
replica.fetch.max.bytes=52428800
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000